# Site
repository: hyungsangpark/CV
favicon: images/favicon.ico

# Content configuration version
version: 3

# Personal info
name: Hyungsang Park
title: Software Engineering Student (Final Year)
email: hyungsangpark@icloud.com
website: https://hyungsangpark.github.io/CV

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: hyungsangpark
# stackoverflow_username: "00000001"
# facebook_username: jekyll
# instagram_username: hsinvade
linkedin_username: hyungsangpark
# pinterest_username: jekyll
# youtube_username: globalmtb

# Additional icon links
additional_links:
  - title: CV in PDF
    icon: fas fa-file-pdf
    url: https://github.com/hyungsangpark/CV/raw/main/CV%20-%20Hyungsang%20Park.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Hyungsang Park. I'm a Software Engineering Student in my final year. 
  My area of interests are frontend and mobile development. 
  I have experiences in web development with React and TypeScript, and in mobile development with React Native and both iOS and Android native development environment. 
  
  Other than development, I am interested in learning new languages, listening to a variety of music, presentation software, and talking with good people in a cafe after a nice meal. 

  I am most skilled in: <mark>React</mark> and <mark>learning different languages</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CodeRacer
        link: https://fearless-frogs-project-webapp.herokuapp.com/
        link_text: CodeRacer - Website
        additional_links:
          - title: Repository for CodeRacer
            icon: fab fa-github
            url: github.com/hyungsangpark/CodeRacer
        quote: >
          "Learn coding by type-racing with others."
        description: | # this will include new lines to allow paragraphs
          CodeRacer enables users to practise the code syntax and familiarise themselves with the frequently used algorithms by typing a block of code in a timed manner. The game supports single player and multiplayer up to 5 players. This project uses <mark>TypeScript</mark>-based MERN stack (<mark>MongoDB</mark>, <mark>Express</mark>, <mark>React</mark>, <mark>Node.js</mark>) and is hosted on Heroku. It was developed by a group of 5 students, and I participated in the development of UI and frontend as well as some <mark>CI/CD</mark> managements.

      - layout: left
        title: Taximeter
        link: github.com/hyungsangpark/Taximeter
        link_text: Project Repository
        additional_links:
          - title: Github Repository for Taximeter
            icon: fab fa-github
            url: github.com/hyungsangpark/Taximeter
        quote: >
          "It's not just taxi drivers who need meters."
        description: | # this will include new lines to allow paragraphs
          I started this project as a way to learn <mark>Swift</mark> and <mark>SwiftUI</mark> for iOS native mobile
          development. What also motivated me was because I was receiving a lot of rides from my friends, 
          and this would be a fun app to turn it on and quantitatively measure the price of the ride. (Of course, with
          an intention to compensate them back üòâ) It uses location services to track the speed of the ride and 
          accumulates rides accordingly to the price specification of Korean taxi price regulations. 

      - layout: left
        title: QTWithMe
        link: https://qtwithme-frontend-2021.azurewebsites.net
        link_text: QTWithMe - Website
        additional_links:
          - title: Frontend Repository for QTWithMe
            icon: fab fa-github
            url: github.com/hyungsangpark/MSA-QTWithMe-Frontend
          - title: Backend Repository for QTWithMe
            icon: fab fa-github
            url: github.com/hyungsangpark/MSA-QTWithMe-Backend
        quote: >
          "Welcome to QTWithMe, share your daily portion of the Bible."
        description: | # this will include new lines to allow paragraphs
          This was a project developed as part of Microsoft Student Accelerator NZ program. 
          I had to develop a full-stack web application that uses <mark>TypeScript React</mark> and <mark>C# .NET</mark> with <mark>GraphQL</mark> as API library. The application is hosted on Azure Web Apps. This application allows you to upload QT texts (short for Quiet Time, a contemplation on a short piece of scripture) and share them with your friends. It uses ESV Bible API to retrieve the scripture texts.

  #      - layout: left
  #        title: Quinzical
  #        link: github.com/hyungsangpark/Quinzical
  #        link_text: Project Repository
  #        additional_links:
  #          - title: hyungsangpark/Quinzical
  #            icon: fab fa-github
  #            url: github.com/hyungsangpark/Quinzical
  #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          #   icon: fab fa-github
  #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #        quote: >
  #          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #        description: | # this will include new lines to allow paragraphs
  #          jdkfjasd

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sylo
        link: https://www.sylo.io/
        link_text: sylo.io
        sub_title: Software Engineer Intern
        caption: Nov 2021 - Feb 2022
        description: | # this will include new lines to allow paragraphs
          I was part of the application team which developed Sylo Mobile application. We used React Native and TypeScript
          to develop a cross-platform mobile application. Some of the tasks I've participated in my internship were 
          solving missing NFT issues, implementing the ability to send multiple medias in chat, and fixing issues on 
          Android devices regarding permissions and multiple concurrent video instances. 
          
          An achievement I've made during this internship is updating the frontend codebase set-up documentation and 
          assisting fellow interns in their set up process. As a result, set up time was dramatically decreased down to 
          20% of previous years.  

  #      - layout: left
  #        title: Electoral Commission
  #        link: https://elections.nz
  #        link_text: elections.nz
  #        sub_title: Issuing Officer & On-Site Translator
  #        caption: Oct 2020 - Oct 2020
  #        description: | # this will include new lines to allow paragraphs
  #          he

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The University of Auckland
        caption: Mar 2019 - Nov 2022
        sub_title: BE (Hons) in Software Engineering
        quote: >
          "Founded in 1883, Auckland is the country‚Äôs largest university with over 40,000 students, nearly 10,000 of whom graduate annually."
        description: | # this will include new lines to allow paragraphs
          I majored in Bachelor of Engineering (Honours) specialising in Software Engineering. From the university, I learned various tools and practices to become a better software engineer. This includes fundamentals of programming like OOP, design patterns, and software engineering principles, to even effective ways to collaborate with colleagues in groups of varying sizes. (from a group of two people to even 20 people)
          
          Some of the achievements I have made during my time at the University of Auckland are:
          - Specialising in Software Engineering (Minimum cohort GPA of A- in first year) 
          - Dean's Honours List for 2020 (Top 5% GPA)
          - Certificate of Outstanding Achievement for 2021 (School of Computer Science)

      - layout: left
        title: Microsoft Student Accelerator
        caption: Mar 2021 - Oct 2021
        quote: >
          "Bridging the gap between university and the workplace."
        description: | # this will include new lines to allow paragraphs
          Microsoft Student Accelerator NZ (short for MSA) is a work-placement program for software developers in New Zealand that provides students a chance to learn and develop full stack web development skills and prove their competence in such skills to the associated industries. As part of the program, I developed QTWithMe as included in the projects section and received a certificate of completion as well as AZ-900: Microsoft Azure Fundamentals Certificate. I also achieved to be eligible for work-place offer after completing the program.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering, some of my other interests and hobbies are:
      - Learning new languages üó£
        - Can natively speak: <mark>English</mark> and <mark>Korean</mark>
        - Can understand and communicate to a some degree: <mark>Chinese</mark> and <mark>Japanese</mark> 
        - Knows a few phrases (learned from friends): <mark>Hindi</mark>
        - Would like to learn in the future: Other European languages, a bit more Chinese and Japanese.
      
      - Listening to a variety of music üéµ
        - K-Pop (mostly old)
        - Classical
        - Jazz
        - Christian Contemporary Music
      
      - Presentation Software üë®üèª‚Äçüíª
        - I have been volunteering at my local church as a presentation team for the last 10 years and so far, I have used ProPresenter and PowerPoint to provide the best worship slide experience to the congregation. 
        - So far, my favourite presentation software in church context is [<mark>ProPresenter</mark>](https://renewedvision.com/propresenter/) because of its powerful ability in managing slides and outside of church context.
      
      - And many more... Meet me to know more about my interests and hobbies. 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
